### ISSUE TITLE
Error message on zip 30328

### ISSUE THREAD

**Issue by InvisibleHandTech** [mariechatfield/call-my-congress#43]
I entered my zip, 30328, on the input screen and received the message “Please provide valid zip code”.  30328 is a valid zip code covering a portion of north Atlanta and Sandy Springs, GA.

**Comment by InvisibleHandTech** [comment]
Error seems to be transient.  It occurred when the iPad tried to prepopulate the address from my profile.  When I opened a new page and entered the zip manually, the correct information loaded.

**Comment by mariechatfield** [comment]
Thanks for opening this issue and closing it when you couldn't reproduce. I tried to repro myself by adding some extra whitespace around the zip, but couldn't get the app to error either. But appreciate you reporting the issue in any case!

**Comment by InvisibleHandTech** [comment]
👌
