### ISSUE TITLE
Improve URLs for permalinks

### ISSUE THREAD

**Issue by zevnyc** [mariechatfield/call-my-congress#53]
I'd like to link to pages of this project in my own project but running into issues with linking.  
Currently pages link like this:  
https://www.callmycongress.com/NY-1  
But it I use this method (industry standard) I'll get a page titled NY 1st, but without the Congressional representative, just statewide (senators):  
https://www.callmycongress.com/NY-01  
Ideally I'd use this format for links:  
https://www.callmycongress.com/NY01

**Comment by mariechatfield** [comment]
This change has just been deployed! Both the test URLs you provided are now supported.
